-- Animals
INSERT INTO "Animal" (name,type) VALUES ('Maisie Strong','Rat');
INSERT INTO "Animal" (name,type) VALUES ('Keefe Watts','Dog');
INSERT INTO "Animal" (name,type) VALUES ('Elliott Duncan','Dog');
INSERT INTO "Animal" (name,type) VALUES ('Emi Landry','Dog');
INSERT INTO "Animal" (name,type) VALUES ('Noelani Trevino','Dog');
INSERT INTO "Animal" (name,type) VALUES ('Mary Williamson','Cat');
INSERT INTO "Animal" (name,type) VALUES ('Cally Blackwell','Hamster');
INSERT INTO "Animal" (name,type) VALUES ('Hiroko Frost','Rat');
INSERT INTO "Animal" (name,type) VALUES ('Robert Kennedy','Cat');
INSERT INTO "Animal" (name,type) VALUES ('Kelly Hines','Cat');
INSERT INTO "Animal" (name,type) VALUES ('Gannon Johnson','Hamster');
INSERT INTO "Animal" (name,type) VALUES ('Cassady Black','Rat');
INSERT INTO "Animal" (name,type) VALUES ('Risa Lucas','Dog');
INSERT INTO "Animal" (name,type) VALUES ('Elaine Austin','Hamster');
INSERT INTO "Animal" (name,type) VALUES ('Melinda Mercer','Hamster');
INSERT INTO "Animal" (name,type) VALUES ('Tanek Chambers','Dog');
INSERT INTO "Animal" (name,type) VALUES ('Keith Bartlett','Rat');
INSERT INTO "Animal" (name,type) VALUES ('Hedwig Bird','Rat');
INSERT INTO "Animal" (name,type) VALUES ('Elijah Cummings','Rat');
INSERT INTO "Animal" (name,type) VALUES ('Quyn Kane','Hamster');
INSERT INTO "Animal" (name,type) VALUES ('Dawn Dalton','Cat');
INSERT INTO "Animal" (name,type) VALUES ('Quon Atkins','Rat');
INSERT INTO "Animal" (name,type) VALUES ('Vernon Holt','Dog');
INSERT INTO "Animal" (name,type) VALUES ('Judith Willis','Rat');
INSERT INTO "Animal" (name,type) VALUES ('Lisandra Robertson','Dog');
INSERT INTO "Animal" (name,type) VALUES ('Bernard Brock','Hamster');
INSERT INTO "Animal" (name,type) VALUES ('Robin Swanson','Cat');
INSERT INTO "Animal" (name,type) VALUES ('Hu Raymond','Rat');
INSERT INTO "Animal" (name,type) VALUES ('Jescie Morrison','Rat');
INSERT INTO "Animal" (name,type) VALUES ('Jerome Whitney','Hamster');
INSERT INTO "Animal" (name,type) VALUES ('Griffin Barnes','Rat');
INSERT INTO "Animal" (name,type) VALUES ('Talon Dotson','Hamster');
INSERT INTO "Animal" (name,type) VALUES ('Kitra Church','Cat');
INSERT INTO "Animal" (name,type) VALUES ('Mia Greer','Hamster');
INSERT INTO "Animal" (name,type) VALUES ('Chastity Baird','Rat');
INSERT INTO "Animal" (name,type) VALUES ('Lucian Garrett','Cat');
INSERT INTO "Animal" (name,type) VALUES ('Chancellor Houston','Hamster');
INSERT INTO "Animal" (name,type) VALUES ('Daphne Moses','Rat');
INSERT INTO "Animal" (name,type) VALUES ('Amery Carver','Rat');
INSERT INTO "Animal" (name,type) VALUES ('Neve Cain','Cat');
INSERT INTO "Animal" (name,type) VALUES ('Martena Booth','Hamster');
INSERT INTO "Animal" (name,type) VALUES ('Kai Bullock','Cat');
INSERT INTO "Animal" (name,type) VALUES ('Kelsie Eaton','Cat');
INSERT INTO "Animal" (name,type) VALUES ('Conan Mckay','Hamster');
INSERT INTO "Animal" (name,type) VALUES ('Griffith Sanford','Rat');
INSERT INTO "Animal" (name,type) VALUES ('Hop Mcknight','Dog');
INSERT INTO "Animal" (name,type) VALUES ('Gail Chen','Dog');
INSERT INTO "Animal" (name,type) VALUES ('Solomon Cabrera','Rat');
INSERT INTO "Animal" (name,type) VALUES ('Lewis Strong','Cat');
INSERT INTO "Animal" (name,type) VALUES ('Blaine Beard','Hamster');
INSERT INTO "Animal" (name,type) VALUES ('Blaine Stokes','Cat');
INSERT INTO "Animal" (name,type) VALUES ('Blaze Christian','Rat');
INSERT INTO "Animal" (name,type) VALUES ('Alana Bradley','Hamster');
INSERT INTO "Animal" (name,type) VALUES ('Lev Bentley','Hamster');
INSERT INTO "Animal" (name,type) VALUES ('Warren Rosales','Rat');
INSERT INTO "Animal" (name,type) VALUES ('Skyler Sharpe','Cat');
INSERT INTO "Animal" (name,type) VALUES ('Arden Slater','Rat');
INSERT INTO "Animal" (name,type) VALUES ('Rajah Guerrero','Cat');
INSERT INTO "Animal" (name,type) VALUES ('Castor Castaneda','Hamster');
INSERT INTO "Animal" (name,type) VALUES ('Clementine Conley','Rat');
INSERT INTO "Animal" (name,type) VALUES ('Lillith Wooten','Cat');
INSERT INTO "Animal" (name,type) VALUES ('Ori Jacobson','Rat');
INSERT INTO "Animal" (name,type) VALUES ('Jeremy Richard','Hamster');
INSERT INTO "Animal" (name,type) VALUES ('Josiah George','Dog');
INSERT INTO "Animal" (name,type) VALUES ('Ingrid Contreras','Cat');
INSERT INTO "Animal" (name,type) VALUES ('Cora Santos','Hamster');
INSERT INTO "Animal" (name,type) VALUES ('Ursa Mckee','Rat');
INSERT INTO "Animal" (name,type) VALUES ('Audrey Compton','Dog');
INSERT INTO "Animal" (name,type) VALUES ('Declan Hanson','Hamster');
INSERT INTO "Animal" (name,type) VALUES ('Hasad Cotton','Dog');
INSERT INTO "Animal" (name,type) VALUES ('Gretchen Mccoy','Dog');
INSERT INTO "Animal" (name,type) VALUES ('Maxwell Mccarthy','Rat');
INSERT INTO "Animal" (name,type) VALUES ('Bevis Parks','Rat');
INSERT INTO "Animal" (name,type) VALUES ('Clayton King','Dog');
INSERT INTO "Animal" (name,type) VALUES ('Anne Chaney','Hamster');
INSERT INTO "Animal" (name,type) VALUES ('Darrel Briggs','Cat');
INSERT INTO "Animal" (name,type) VALUES ('Quamar Andrews','Dog');
INSERT INTO "Animal" (name,type) VALUES ('Wilma Vega','Cat');
INSERT INTO "Animal" (name,type) VALUES ('Amelia Cox','Rat');
INSERT INTO "Animal" (name,type) VALUES ('Jorden Chapman','Rat');
INSERT INTO "Animal" (name,type) VALUES ('Eugenia Mosley','Hamster');
INSERT INTO "Animal" (name,type) VALUES ('Jakeem Reed','Hamster');
INSERT INTO "Animal" (name,type) VALUES ('Vaughan Duke','Dog');
INSERT INTO "Animal" (name,type) VALUES ('Molly Macdonald','Cat');
INSERT INTO "Animal" (name,type) VALUES ('Ali Castro','Dog');
INSERT INTO "Animal" (name,type) VALUES ('Kyra Combs','Rat');
INSERT INTO "Animal" (name,type) VALUES ('Jerry Barton','Hamster');
INSERT INTO "Animal" (name,type) VALUES ('Patrick Mejia','Dog');
INSERT INTO "Animal" (name,type) VALUES ('Jasper James','Cat');
INSERT INTO "Animal" (name,type) VALUES ('Nehru Blankenship','Rat');
INSERT INTO "Animal" (name,type) VALUES ('Edan Garrison','Dog');
INSERT INTO "Animal" (name,type) VALUES ('Paul Bradford','Hamster');
INSERT INTO "Animal" (name,type) VALUES ('Shelly Barnes','Dog');
INSERT INTO "Animal" (name,type) VALUES ('Rose Fisher','Cat');
INSERT INTO "Animal" (name,type) VALUES ('Geoffrey Serrano','Rat');
INSERT INTO "Animal" (name,type) VALUES ('Quincy Levy','Cat');
INSERT INTO "Animal" (name,type) VALUES ('Ruth Randolph','Dog');
INSERT INTO "Animal" (name,type) VALUES ('Elliott Lott','Rat');
INSERT INTO "Animal" (name,type) VALUES ('Blythe Chaney','Hamster');
INSERT INTO "Animal" (name,type) VALUES ('Alana Pate','Cat');

-- Owners
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Merritt','Skinner','Russell');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Ryan','Ruiz','Reuben');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Amaya','Figueroa','Erich');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Cain','Molina','Byron');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Lewis','Grimes','Ronan');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Axel','Hamilton','Wayne');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Barbara','Moses','Ethan');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Catherine','Olson','August');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Quintessa','Watson','Merrill');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Mason','Johnson','Cyrus');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Constance','Doyle','Nasim');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Kyra','Ingram','Kennan');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Florence','Jimenez','Davis');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Tarik','Summers','Orson');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Daquan','Little','Ciaran');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Jane','Hall','Eric');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Teegan','Bonner','Eric');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Sean','Cannon','Levi');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Cade','Hull','Macon');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Lunea','Noble','Isaiah');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Vance','Levine','Levi');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Tanek','Brewer','Calvin');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Edward','Huffman','Brandon');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Geoffrey','Buck','Travis');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Alec','Townsend','Caldwell');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Acton','Nichols','Zachary');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Nora','Ochoa','Dale');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Russell','Richards','Kennedy');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Marny','Hess','Rooney');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Florence','Petty','Lyle');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('MacKenzie','Washington','Amal');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Amy','Solis','Lars');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Valentine','Cruz','Russell');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Deacon','Burks','Moses');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Iona','Blake','Levi');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Ina','Flynn','Reed');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Hedwig','Bowen','Allistair');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Kieran','Delacruz','Eagan');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Neve','Yang','Rafael');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Malachi','Greer','Abraham');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Asher','Webb','Ezekiel');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Kelly','Mccormick','Hasad');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Octavius','Rice','Kyle');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Logan','Swanson','Price');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Sarah','Spence','Tucker');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Blair','Morton','Gabriel');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Kiona','Figueroa','Aristotle');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Kuame','Stanton','Nolan');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Merritt','Reid','Trevor');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Alexander','Stokes','Garrett');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Cheryl','Moody','Gavin');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Tyler','Morin','Timothy');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Yuri','Holloway','Keane');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Rebekah','Hyde','Deacon');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Damian','Williams','Cody');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Elijah','Francis','Mark');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Keith','Grant','Tiger');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Nigel','Foley','Hedley');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('William','Donovan','Hall');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Gail','Christensen','Dennis');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Gray','Rosario','Holmes');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Vincent','Kelley','Seth');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Finn','Prince','Carl');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Quincy','Dawson','Emmanuel');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Jocelyn','Bradshaw','Rahim');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Ulric','Horne','Xenos');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Malcolm','Mays','Ronan');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Jaquelyn','Casey','Clinton');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Otto','Mckinney','Paki');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Jaden','Nielsen','Rajah');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Yvonne','Livingston','Andrew');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Ira','Salazar','Zephania');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Hiram','Acevedo','Rigel');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Hanae','Ball','Ryder');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Chancellor','Duncan','Marvin');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Reece','Carter','Abel');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Hilary','Mayer','Castor');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Benedict','Harvey','Finn');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Jordan','Lawson','Chancellor');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Rhiannon','Rich','Beau');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Sacha','Lynn','Quentin');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Minerva','Guthrie','Kasimir');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Virginia','Cooper','Ferdinand');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Iola','Dickerson','Macon');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Julie','Sawyer','Eric');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Deirdre','Pace','Lucius');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Jasmine','Foster','Derek');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Noel','Pollard','Travis');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Zeus','Downs','Wesley');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Alec','Barnes','Silas');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Rama','Rutledge','Dale');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Ciaran','Fitzpatrick','Isaac');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Joshua','Strong','Burton');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Sydney','Flores','Thor');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Alexandra','Mercer','Colin');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Alfonso','Nunez','Keegan');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Vanna','Valencia','Laith');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Wynne','Moss','Kermit');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Quintessa','Myers','Kenneth');
INSERT INTO "Owner" (first_name,last_name,middle_name) VALUES ('Naida','Holman','Nasim');

-- OwnerAnimals
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (8,7);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (4,4);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (2,1);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (2,10);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (1,9);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (8,1);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (7,10);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (10,5);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (4,8);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (4,8);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (8,2);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (1,7);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (2,8);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (1,5);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (1,8);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (1,3);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (1,8);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (4,1);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (6,8);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (6,8);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (6,8);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (5,4);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (2,4);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (2,2);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (7,5);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (1,7);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (2,7);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (8,6);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (1,2);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (7,10);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (8,7);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (5,4);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (10,3);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (3,6);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (1,10);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (1,4);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (1,5);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (10,1);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (5,1);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (9,4);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (10,7);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (3,5);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (8,5);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (1,1);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (7,7);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (7,2);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (3,9);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (4,8);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (9,3);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (10,9);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (9,6);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (9,10);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (6,2);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (10,3);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (2,10);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (9,3);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (8,9);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (1,1);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (3,10);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (9,2);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (6,5);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (4,1);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (3,3);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (1,7);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (8,10);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (1,9);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (10,8);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (1,2);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (7,4);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (10,8);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (5,4);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (3,8);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (8,9);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (2,3);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (6,8);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (10,6);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (4,8);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (3,5);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (3,3);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (10,3);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (8,3);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (4,6);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (1,9);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (10,3);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (4,9);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (4,6);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (7,4);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (2,4);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (10,5);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (8,5);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (4,6);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (2,8);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (5,7);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (9,7);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (4,1);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (4,2);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (3,7);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (4,7);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (1,10);
INSERT INTO "OwnerAnimal" (animal_id,owner_id) VALUES (2,7);